timer.bat g++ -fdiagnostics-color=always -g -Wall -std=c++17 ^
-IC:/Users/ramen/Projects/Minecraft/include ^
-IC:/Users/ramen/Clibrary ^
./src/main.cpp ^
./src/game.cpp ^
./src/window.cpp ^
./src/shader.cpp ^
./src/texture.cpp ^
./src/camera.cpp ^
./src/attribute.cpp ^
./src/buffer.cpp ^
./src/block.cpp ^
./src/subtexture.cpp ^
./src/renderer.cpp ^
./src/lighting.cpp ^
./src/ray.cpp ^
./src/glmath.cpp ^
./src/material.cpp ^
-c ^